/*
 * Generated by MTK SP Drv_CodeGen Version 03.13.6 for MT6575_NP. Copyright MediaTek Inc. (C) 2013.
 * Thu Sep 18 03:44:28 2014
 * Do Not Modify the File.
 */

#ifndef __CUST_AUXADC_TOOL_H
#define __CUST_AUXADC_TOOL_H


#define AUXADC_HF_MIC_CHANNEL     1
#define AUXADC_TEMPERATURE_CHANNEL     3
#define AUXADC_LCD_ID_CHANNEL     4


#endif //_CUST_AUXADC_TOOL_H


