/*
 * Generated by MTK SP Drv_CodeGen Version 03.13.6  for MT6575_NP. Copyright MediaTek Inc. (C) 2013.
 * Thu Sep 18 03:44:28 2014
 * Do Not Modify the File.
 */



#include <mach/upmu_sw.h>


//****for customer use*******// 


//PMIC default enable/disable result

//PMIC mode select 
typedef enum
{
   BY_ENABLE = 0,
   BY_SRCLKEN = 1
}MODE_sel_enum;

////For Common use 

//For PMIC driver use




